runtime: nodejs20

# Optional: increase memory and timeout for PDF generation
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Optional: increase request timeout for PDF generation
automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65
